import type { Contractor, Review, LicenseApplication } from '@/types';

export const serviceCategories: string[] = [
  'Air Conditioning',
  'Appliance Repair',
  'Asbestos Removal',
  'Attic Restoration',
  'Basement Renovations',
  'Basement Waterproofing',
  'Bathroom Renovations',
  'Brick Builder (Masonry)',
  'Cabinet Builder',
  'Cabinet Refacing',
  'Ceramic Installation',
  'Chimney Sweep',
  'Closets',
  'Concrete Contractors',
  'Concrete Lifting',
  'Drywall Contractors',
  'Electrical',
  'Exterminator',
  'Exterior Renovations',
  'Flooring',
  'Furnace Installation',
  'Furnace Repair',
  'Garage Builders',
  'Garage Door Repair',
  'General Construction',
  'Gutter Cleaning',
  'HVAC',
  'Handyman Services',
  'Home Cleaning',
  'Home Security',
  'House Lifting',
  'Insulation',
  'Interior Design',
  'Irrigation',
  'Junk Removal',
  'Kitchen Renovations',
  'Landscaping',
  'Major Renovations',
  'Moving',
  'Painting',
  'Plastering',
  'Plumbing',
  'Poly B Replacement',
  'Pool Repair',
  'Roofing',
  'Siding',
  'Smart Home Installation',
  'Water Heater Installation',
  'Window Cleaning',
  'Window Coverings',
  'Windows and Doors',
];

export const canadianProvincesAndCities = [
    { province: 'Alberta', cities: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'] },
    { province: 'British Columbia', cities: ['Vancouver', 'Victoria', 'Kelowna', 'Surrey'] },
    { province: 'Manitoba', cities: ['Winnipeg', 'Brandon'] },
    { province: 'New Brunswick', cities: ['Fredericton', 'Moncton', 'Saint John'] },
    { province: 'Newfoundland and Labrador', cities: ['St. John\'s', 'Corner Brook'] },
    { province: 'Nova Scotia', cities: ['Halifax', 'Sydney'] },
    { province: 'Ontario', cities: ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton', 'London'] },
    { province: 'Quebec', cities: [
      'Blainville',
      'Brossard',
      'Châteauguay',
      'Côte-Saint-Luc',
      'Dorval',
      'Drummondville',
      'Gatineau',
      'Granby',
      'Joliette',
      'Kirkland',
      'Lachute',
      'La Prairie',
      'L\'Assomption',
      'Laval',
      'Lévis',
      'Longueuil',
      'Mirabel',
      'Montreal',
      'Pointe-Claire',
      'Quebec City',
      'Rimouski',
      'Saguenay',
      'Saint-Constant',
      'Saint-Eustache',
      'Saint-Georges',
      'Saint-Hyacinthe',
      'Saint-Jean-sur-Richelieu',
      'Saint-Jérôme',
      'Sainte-Thérèse',
      'Salaberry-de-Valleyfield',
      'Sherbrooke',
      'Sorel-Tracy',
      'Terrebonne',
      'Thetford Mines',
      'Trois-Rivières',
      'Val-d\'Or'] },
    { province: 'Saskatchewan', cities: ['Saskatoon', 'Regina'] },
    { province: 'Prince Edward Island', cities: ['Charlottetown', 'Summerside'] },
];

export const mockReviews: Review[] = [
  {
    id: 'review1',
    reviewerName: 'Alice Johnson',
    revieweeId: 'contractor1',
    rating: 5,
    title: 'Amazing Work!',
    comment: 'John and his team were fantastic. Professional, on-time, and the result exceeded our expectations. Highly recommend for any kitchen renovation!',
    createdAt: '2023-10-15T10:00:00Z',
    contractorComment: 'Thank you, Alice! It was a pleasure working with you.'
  },
  {
    id: 'review2',
    reviewerName: 'Bob Williams',
    revieweeId: 'contractor1',
    rating: 4,
    title: 'Good service',
    comment: 'Did a good job on our bathroom. There was a slight delay but the final quality was great.',
    createdAt: '2023-09-20T14:30:00Z',
  },
  {
    id: 'review3',
    reviewerName: 'Charlie Brown',
    revieweeId: 'contractor2',
    rating: 5,
    title: 'Excellent Electrician',
    comment: 'Jane fixed a complex electrical issue that two other electricians couldn\'t figure out. She was efficient and very knowledgeable. A true expert!',
    createdAt: '2023-11-01T11:00:00Z',
  },
  {
    id: 'review4',
    reviewerName: 'Diana Prince',
    revieweeId: 'contractor3',
    rating: 3,
    title: 'Could be better',
    comment: 'The plumbing job was okay, but communication could have been improved. The work was completed but it was hard to get updates.',
    createdAt: '2023-10-25T16:00:00Z',
  },
];


export const mockContractors: Contractor[] = [
  {
    id: 'contractor1',
    name: 'John Doe Renovations',
    email: 'john.doe.reno@example.com',
    location: 'Montreal, Quebec',
    serviceCategories: ['General Construction'],
    bio: 'With over 15 years of experience in the construction industry, my team and I specialize in high-quality home renovations. We pride ourselves on attention to detail and customer satisfaction. Let\'s build your dream space together.',
    profilePictureUrl: 'https://placehold.co/200x200.png',
    profilePictureStatus: 'approved',
    averageRating: 4.5,
    reviews: mockReviews.filter(r => r.revieweeId === 'contractor1'),
    languagePreferences: ['english'],
    licenseNumber: 'ON-123456',
    isLicenseApproved: true,
    availability: 'Mon-Fri, 9am-5pm',
    website: 'https://www.johndoerenovations.com',
    phone: '514-555-1234',
    socialLinks: {
      facebook: 'https://www.facebook.com/johndoerenovations',
      instagram: 'https://www.instagram.com/johndoerenovations',
    },
  },
  {
    id: 'contractor2',
    name: 'Jane Smith Electric',
    email: 'jane.smith.electric@example.com',
    location: 'Montreal, Quebec',
    serviceCategories: ['General Construction'],
    bio: 'Certified master electrician providing safe and reliable electrical services. From simple repairs to full home wiring and smart home setups, I ensure every job is done to code and to the highest standard.',
    profilePictureUrl: 'https://placehold.co/200x200.png',
    profilePictureStatus: 'pending',
    averageRating: 5,
    reviews: mockReviews.filter(r => r.revieweeId === 'contractor2'),
    languagePreferences: ['english', 'french'],
    licenseNumber: 'BC-654321',
    isLicenseApproved: true,
    availability: 'Available for emergency calls',
  },
  {
    id: 'contractor3',
    name: 'Les Plombiers Réunis',
    email: 'plombiers.reunis@example.com',
    location: 'Montreal, Quebec',
    serviceCategories: ['General Construction'],
    bio: 'Votre expert en plomberie à Montréal. Service rapide, fiable et courtois pour toutes urgences et installations. Nous parlons français et anglais.',
    profilePictureUrl: 'https://placehold.co/200x200.png',
    averageRating: 3,
    reviews: mockReviews.filter(r => r.revieweeId === 'contractor3'),
    languagePreferences: ['french', 'english'],
    licenseNumber: 'QC-789123',
    isLicenseApproved: false,
    availability: '24/7',
  },
  {
    id: 'contractor4',
    name: 'Green Thumb Landscaping',
    email: 'greenthumb@example.com',
    location: 'Montreal, Quebec',
    serviceCategories: ['General Construction'],
    bio: 'Transforming outdoor spaces into beautiful, functional landscapes. We offer design, installation, and maintenance services to bring your garden dreams to life.',
    profilePictureUrl: 'https://placehold.co/200x200.png',
    averageRating: 4.8,
    reviews: [],
    languagePreferences: ['english'],
    licenseNumber: 'AB-456789',
    isLicenseApproved: true,
  },
];

export const mockLicenseApplications: LicenseApplication[] = [
  {
    id: 'app1',
    contractorId: 'contractor3',
    contractorName: 'Les Plombiers Réunis',
    licenseNumber: 'QC-789123',
    licenseDocumentUrl: '/mock-license.pdf',
    status: 'pending',
    submittedAt: '2023-11-05T09:00:00Z',
  },
  {
    id: 'app2',
    contractorId: 'new-contractor-1',
    contractorName: 'Future Electricians',
    licenseNumber: 'ON-987654',
    status: 'pending',
    submittedAt: '2023-11-04T15:30:00Z',
  },
   {
    id: 'app3',
    contractorId: 'contractor2',
    contractorName: 'Jane Smith Electric',
    licenseNumber: 'BC-654321',
    status: 'approved',
    submittedAt: '2023-10-20T10:00:00Z',
    reviewedAt: '2023-10-21T11:00:00Z',
  },
  {
    id: 'app4',
    contractorId: 'old-contractor-2',
    contractorName: 'Rejected Plumbing Co.',
    licenseNumber: 'QC-112233',
    status: 'rejected',
    submittedAt: '2023-09-15T14:00:00Z',
    reviewedAt: '2023-09-16T18:00:00Z',
    reviewerNotes: 'Provided document was expired.'
  },
];
